baseURL = "/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Paradise City Festival 2020"

[params]
  author = "Studio Colibri"
  description = "5, 6 & 7 July in Perk, Belgium"
  mainSections = ["static", "news", "lineup", "home"]

disableKinds = ["taxonomy", "taxonomyTerm"]

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5
  
 [imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "box"

# Default JPEG quality setting. Default is 75.
quality = 55

# Anchor used when cropping pictures.
# Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
# Smart Cropping is content aware and tries to find the best crop for each image.
# Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
anchor = "smart"