---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: MAIN PAGES
- type: document
  path: content/_index.md
  label: Homepage
- type: document
  path: content/green.md
  label: Green
- type: document
  path: content/practical.md
  label: Practical
- type: document
  path: content/transport.md
  label: Transport
- type: heading
  label: BLOG
- type: directory
  path: content/news
  label: News
  create: documents
  match: "**/*"
  templates:
  - blog-post
- type: heading
  label: FESTIVAL
- type: directory
  path: content/artist
  label: Artists
  create: all
  match: "**/*"
  templates:
  - artist
- type: directory
  path: content/stages
  label: Stages
  create: documents
  match: "**/*"
  templates:
  - stages
- type: directory
  path: content/timetable
  label: Timetable
  create: all
  match: "**/*"
- type: document
  path: content/partners.md
  label: Partners
- type: heading
  label: LANDING PAGES
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: heading
  label: OTHER
upload_dir: ''
public_path: https://res.cloudinary.com/dxswtxauo/image/upload/w_1000/f_auto
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.61
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.52'
